import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { Hanken_Grotesk } from "next/font/google";

import { cookieToInitialState } from "wagmi";

import { config } from "@/config";
import { Web3Modal } from "@/context/index";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const hanken: any = Hanken_Grotesk({
  subsets: ["latin"],
  weight: "600",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en" className={hanken.className}>
      <body className="bg-mint-100">
        <Web3Modal initialState={initialState}>
          <Navbar />
          {children}
        </Web3Modal>
      </body>
    </html>
  );
}
